#!/usr/bin/env python3
"""Build the Comigo landing page: inlines site/assets images into index.template.html
as data URIs, producing a single self-contained site/index.html.

Usage: python3 site/build.py
"""
import hashlib, re, os, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))

# Images are emitted as separate, content-hashed static files (served under
# /assets/ with immutable caching) instead of base64 data URIs. Each is capped
# at 640px wide (2x the largest rendered size) and encoded as WebP when that
# is meaningfully smaller than the original; the tag gets explicit
# width/height so nothing shifts while it loads.
DIST = os.path.join(here, 'assets-dist')
os.makedirs(DIST, exist_ok=True)
for f in os.listdir(DIST):
    os.remove(os.path.join(DIST, f))

def process(name):
    for ext in ('jpg', 'png'):
        p = os.path.join(here, 'assets', f'{name}.{ext}')
        if os.path.exists(p):
            break
    else:
        sys.exit(f'missing asset: {name}')
    tmp = os.path.join(DIST, f'.{name}.webp')
    r = subprocess.run(['node', os.path.join(here, 'img-webp.js'), p, tmp], capture_output=True, text=True)
    if r.returncode:
        sys.exit(f'webp encode failed for {name}: {r.stderr.strip()}')
    webp_wh, orig_wh = r.stdout.split()
    webp = open(tmp, 'rb').read(); os.remove(tmp)
    orig = open(p, 'rb').read()
    if len(webp) < len(orig) * 0.9:
        data, ext_out, (w, h) = webp, 'webp', webp_wh.split('x')
    else:
        data, ext_out, (w, h) = orig, ext, orig_wh.split('x')
    fname = f'{name}.{hashlib.md5(data).hexdigest()[:8]}.{ext_out}'
    open(os.path.join(DIST, fname), 'wb').write(data)
    return f'/assets/{fname}', w, h

manifest = {}
def repl(m):
    name = m.group(1)
    if name not in manifest:
        manifest[name] = process(name)
    url, w, h = manifest[name]
    return f'src="{url}" width="{w}" height="{h}"'

# {{AUD_name}} -> site/audio/name.mp3, content-hashed into assets-dist like
# images. The token is replaced wherever it appears (src=, data-audio=,
# embedded JSON word data, ...).
aud_manifest = {}
def aud_repl(m):
    name = m.group(1)
    if name not in aud_manifest:
        p = os.path.join(here, 'audio', f'{name}.mp3')
        if not os.path.exists(p):
            sys.exit(f'missing audio asset: {name}')
        data = open(p, 'rb').read()
        fname = f'{name}.{hashlib.md5(data).hexdigest()[:8]}.mp3'
        open(os.path.join(DIST, fname), 'wb').write(data)
        aud_manifest[name] = f'/assets/{fname}'
    return aud_manifest[name]

def build(tmpl_name, out_name):
    html = open(os.path.join(here, tmpl_name)).read()
    # Shared navigation: {{NAV}} pulls in site/nav.html, with the current
    # page's link marked (aria-current) so it can be styled subtly.
    if '{{NAV}}' in html:
        nav = open(os.path.join(here, 'nav.html')).read()
        slug = out_name[:-len('.html')]
        nav = nav.replace(f'data-nav="{slug}"', f'data-nav="{slug}" aria-current="page"')
        html = html.replace('{{NAV}}', nav)
    out = re.sub(r'src="\{\{IMG_([\w-]+)\}\}"', repl, html)
    out = re.sub(r'\{\{AUD_([\w-]+)\}\}', aud_repl, out)
    if '{{IMG_' in out or '{{AUD_' in out:
        sys.exit(f'unreplaced token remains in {tmpl_name}')
    # Interactive sample pages: inline the bubble/audio data generated by
    # build-pages-data.py.
    pages_js_path = os.path.join(here, 'interactive-pages.js')
    if '{{PAGES_JS}}' in out:
        if not os.path.exists(pages_js_path):
            sys.exit('run build-pages-data.py first (interactive-pages.js missing)')
        out = out.replace('{{PAGES_JS}}', open(pages_js_path).read())
    # The template has no document skeleton (it doubles as a Claude Artifact
    # source, which supplies its own). Split at the end of the style block and wrap.
    head, sep, body = out.partition('</style>')
    if not sep:
        sys.exit(f'{tmpl_name} missing </style>')
    # OpenAI conversion pixel — injected into every built page's head.
    oai_pixel = ('<script>!function(w,d,s,u){if(w.oaiq)return;var q=function(){q.q.push(arguments)};q.q=[];'
                 'w.oaiq=q;var j=d.createElement(s);j.async=1;j.src=u;var f=d.getElementsByTagName(s)[0];'
                 'f.parentNode.insertBefore(j,f)}(window,document,"script","https://bzrcdn.openai.com/sdk/oaiq.min.js");'
                 'oaiq("init",{pixelId:"TvYodr4Ct4JBQ2GkX5u1gK"});</script>')
    doc = ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
           + head + sep + '\n' + oai_pixel + '\n</head>\n<body>' + body + '\n</body>\n</html>\n')
    open(os.path.join(here, out_name), 'w').write(doc)
    print(f'site/{out_name} written,', os.path.getsize(os.path.join(here, out_name)), 'bytes')

# Every *.template.html builds to its .html twin — index plus any SEO/story
# pages; new pages need only a template file (the sitemap picks them up too).
for tmpl in sorted(f for f in os.listdir(here) if f.endswith('.template.html')):
    build(tmpl, tmpl.replace('.template.html', '.html'))

total = sum(os.path.getsize(os.path.join(DIST, f)) for f in os.listdir(DIST))
print(f'assets-dist: {len(os.listdir(DIST))} files, {total / 1024:.0f} KB')
